# -*- coding: utf-8 -*-
"""ödev.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G7URUt0X7fST9M6lJTth2-MzDs_kmmJQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def calculate_koi(bod5, cod):
    return (cod - bod5) / bod5

def calculate_boi5(bod5):
    return bod5

def calculate_nh4n(total_nitrogen, no3n):
    return total_nitrogen - no3n

def calculate_po4p(total_phosphorus, po4p):
    return total_phosphorus - po4p

def plot_line_chart(x, y, x_label, y_label, title):
    plt.figure(figsize=(8, 6))
    plt.plot(x, y, marker='o', linestyle='-', color='b')
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)
    plt.show()

def plot_bar_chart(x, y, x_label, y_label, title):
    plt.figure(figsize=(8, 6))
    sns.barplot(x=x, y=y, palette='viridis')
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)
    plt.show()

bod5_value = float(input('BOD5 değerini girin (mg/L):'))
cod_value = float(input('COD değerini girin (mg/L): '))
total_nitrogen_value = float(input('Toplam Azot değerini girin (mg/L):'))
no3n_value = float(input('NO3-N değerini girin (mg/L): '))
total_phosphorus_value = float(input('Toplam Fosfor değerini girin (mg/L): '))
po4p_value = float(input('PO4-P değerini girin (mg/L): '))

koi_result = calculate_koi(bod5_value, cod_value)
boi5_result = calculate_boi5(bod5_value)
nh4n_result = calculate_nh4n(total_nitrogen_value, no3n_value)
po4p_result = calculate_po4p(total_phosphorus_value, po4p_value)

plot_line_chart([1, 2, 3, 4, 5], [10, 12, 8, 15, 20], 'X Ekseni', 'Y Ekseni', 'Çizgi Grafiği Örneği')
plot_bar_chart(['A', 'B', 'C', 'D', 'E'], [30, 25, 40, 20, 35], 'Kategoriler', 'Değerler', 'Sütun Grafiği Örneği')